# Generated by Django 2.2.5 on 2021-08-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20210716_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
